apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp-j
  ports:
    - port: 80
  selector:
    app: myapp-j
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-j
  labels:
    app: myapp-j
spec:
  selector:
    matchLabels:
      app: myapp-j
  strategy:
    type: Never
  template:
    metadata:
      labels:
        app: myapp-j   
    spec:
      containers:
      - image: shalligoel/training:hellonode-k8s
        name: myapp-j
        ports:
        - containerPort: 8000
          name: myapp-j